### PR TITLE
add java utility to consume suspend functions and move package

### PR DESCRIPTION
**Pull request by GiviMAD**
Signed-off-by: Miguel Álvarez Díez <miguelwork92@gmail.com>

Hi again. 
Still missing another util to consume all the sdk utilities from Java. I have added it next to the JavaFlow and I've moved the package with the two utils to the root of the core.
I have tried to implement it similar to what we did with the JavaFlow, it can be used as follows:
```java
suspendFn(..., JavaContinuation.get((err, result)->{
            // ...
}));
```
Hope everything is correct.
Regards

### CODE REVIEW

**Comment by nielsvanvelzen** [comment]
We already have the `JavaCallback` for all API operations. What places are you trying to use that need another continuation implementation?

**Comment by GiviMAD** [comment]
I can't use the recommendation functions for the discovery nether the publish function in the WebsocketApi. Also with JavaCallback and JavaDataCallback I can not access the exceptions in case them occur, which is desirable some places of my code.

**Comment by GiviMAD** [comment]
I have made some changes to make it more similar to the JavaCallback util.
If you think is better that I close the pr and wait for a different solution let me know.

**Comment by nielsvanvelzen** [comment]
Thanks for the explanation. I'd like to have consistency between our various continuation implementations. After your explanation I thought of a few things I want to change:

- Add a way to receive errors in all continuations (JavaCallback/JavaDataCallback)
  - Optional to implement, defaults to throwing
- Add a new continuation for non-api functions (this PR)

For the second item I'm thinking of changing JavaCallback to work for all types, not only Response<...> types.

It will look something like this:

```java
// Based on the java-cli sample code

userApi.authenticateUserByName(new AuthenticateUserByName("demo", null, ""), new JavaResponseCallback<AuthenticationResult>() {
    @Override
    public void onResponse(@Nullable AuthenticationResult response) {
        System.out.println("Access token is " + response.getAccessToken());
    }

    @Override
    public void onError(@Nullable Throwable error) {
        System.err.println("Something went wrong!!");
        error.printStackTrace();
    }
});
```

I'll thinker a bit about it and create a new pull request with those changes. Let me know if you have any thoughts about it.

**Comment by GiviMAD** [comment]
The idea sounds great, so I'll close this one. Thanks for the help.

**Pull request closed without merging**
