### PR TITLE
Update OpenAPI to 10.8.0-beta.2

### PR DESCRIPTION
**Pull request by nielsvanvelzen**
Adds some configuration models that were added. They're used in updateNamedConfiguration() as JsonElement.

I found one issue in the spec, maybe @crobibero can look at it:

Schema:

```json
      "GuidStringValueTuple": {
        "type": "object",
        "additionalProperties": false
      },
```

Generated code:

https://github.com/jellyfin/jellyfin-sdk-kotlin/blob/18a14516a4ff7c55f0be9ec76104a8c237a7f666/jellyfin-model/src/commonMain/kotlin-generated/org/jellyfin/sdk/model/api/GuidStringValueTuple.kt#L1-L11

I guess it should look more like the NameGuidPair/NameIdPair/etc? It's used in the MigrationOptions model.

### CODE REVIEW

**Review by Maxr1998 — APPROVED** [review]
Seems good to me. Let me know when I can merge.

**Comment by nielsvanvelzen** [comment]
Yeah we can merge this one, just need to make sure the mentioned issues gets fixed in the next beta. I'll ping some people on Matrix for that.

**Comment by crobibero** [comment]
I have this on my TODO list but my keyboard decided to stop working halfway through yesterday... 

Hoping it works today so I can look :)

**Comment by nielsvanvelzen** [comment]
@crobibero do you have some time to look at this before release? 👀

**Pull request merged**
